# Generated by Django 6.0.3 on 2026-04-02 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('category', models.CharField(choices=[('dowod', 'Dowód osobisty'), ('paszport', 'Paszport'), ('prawo_jazdy', 'Prawo jazdy'), ('ubezpieczenie', 'Ubezpieczenie'), ('przeglad', 'Przegląd samochodu'), ('smieci', 'Wywóz śmieci'), ('rachunki', 'Rachunki / opłaty'), ('lekarz', 'Wizyta u lekarza'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Kategoria')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('due_date', models.DateField(verbose_name='Termin')),
                ('remind_days_before', models.PositiveIntegerField(default=7, verbose_name='Przypomnij dni przed terminem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przypomnienie',
                'verbose_name_plural': 'Przypomnienia',
                'ordering': ['due_date'],
            },
        ),
    ]
