# Generated by Django 6.0.3 on 2026-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Wykonane'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[('none', 'Bez powtarzania'), ('weekly', 'Co tydzień'), ('biweekly', 'Co 2 tygodnie'), ('monthly', 'Co miesiąc'), ('quarterly', 'Co kwartał'), ('yearly', 'Co rok')], default='none', max_length=20, verbose_name='Powtarzanie'),
        ),
    ]
