# Generated by Django 6.0.3 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_is_done_reminder_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('dowod', 'Dowód osobisty'), ('paszport', 'Paszport'), ('prawo_jazdy', 'Prawo jazdy'), ('ubezpieczenie', 'Ubezpieczenie'), ('przeglad', 'Przegląd samochodu'), ('smieci', 'Wywóz śmieci'), ('rachunki', 'Rachunki / opłaty'), ('lekarz', 'Wizyta u lekarza'), ('studia', 'Studia / egzamin'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Kategoria'),
        ),
    ]
