# Generated by Django 6.0.3 on 2026-04-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('event_type', models.CharField(choices=[('wolne', 'Dzień wolny'), ('egzamin', 'Egzamin'), ('kolokwium', 'Kolokwium'), ('projekt', 'Oddanie projektu'), ('spotkanie', 'Spotkanie'), ('wyjazd', 'Wyjazd / urlop'), ('impreza', 'Impreza / wydarzenie'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('date', models.DateField(verbose_name='Data')),
                ('end_date', models.DateField(blank=True, help_text='Zostaw puste jeśli jednodniowe', null=True, verbose_name='Data końcowa')),
                ('all_day', models.BooleanField(default=True, verbose_name='Cały dzień')),
                ('time', models.TimeField(blank=True, help_text='Opcjonalnie, jeśli nie cały dzień', null=True, verbose_name='Godzina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['date', 'time'],
            },
        ),
    ]
