# Generated by Django 6.0.3 on 2026-04-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wolne', 'Dzień wolny'), ('zajecia', 'Zajęcia'), ('egzamin', 'Egzamin'), ('kolokwium', 'Kolokwium'), ('projekt', 'Oddanie projektu'), ('spotkanie', 'Spotkanie'), ('wyjazd', 'Wyjazd / urlop'), ('impreza', 'Impreza / wydarzenie'), ('inne', 'Inne')], default='inne', max_length=30, verbose_name='Typ'),
        ),
        migrations.CreateModel(
            name='DayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('subject', models.CharField(max_length=200, verbose_name='Przedmiot')),
                ('note', models.TextField(blank=True, verbose_name='Notatka / co do zrobienia')),
                ('has_quiz', models.BooleanField(default=False, verbose_name='Wejściówka')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Punkty z wejściówki')),
                ('quiz_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max punktów')),
                ('homework', models.TextField(blank=True, verbose_name='Zadanie domowe / do zrobienia')),
                ('is_done', models.BooleanField(default=False, verbose_name='Zrobione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notatka dnia',
                'verbose_name_plural': 'Notatki dnia',
                'ordering': ['date', 'subject'],
            },
        ),
    ]
