# Generated by Django 6.0.3 on 2026-04-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_alter_event_event_type_daynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='daynote',
            name='calendar_bg',
            field=models.CharField(blank=True, choices=[('', 'Brak'), ('#e8f0fe', 'Niebieski'), ('#fef2f2', 'Różowy'), ('#fef9c3', 'Żółty'), ('#dcfce7', 'Zielony'), ('#f3e8ff', 'Fioletowy'), ('#fff7ed', 'Pomarańczowy'), ('#f0f9ff', 'Jasny niebieski'), ('#fdf2f8', 'Jasny różowy')], default='', max_length=10, verbose_name='Kolor tła w kalendarzu'),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_bg',
            field=models.CharField(blank=True, choices=[('', 'Brak'), ('#e8f0fe', 'Niebieski'), ('#fef2f2', 'Różowy'), ('#fef9c3', 'Żółty'), ('#dcfce7', 'Zielony'), ('#f3e8ff', 'Fioletowy'), ('#fff7ed', 'Pomarańczowy'), ('#f0f9ff', 'Jasny niebieski'), ('#fdf2f8', 'Jasny różowy')], default='', max_length=10, verbose_name='Kolor tła w kalendarzu'),
        ),
    ]
