# Generated by Django 6.0.3 on 2026-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_daynote_calendar_bg_event_calendar_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynote',
            name='subject',
            field=models.CharField(choices=[('zts', 'Zaawansowane technologie sieciowe'), ('gbd', 'Grafowe bazy danych'), ('sem', 'Seminarium'), ('pw', 'Programowanie współbieżne'), ('python', 'Programowanie w języku Python'), ('cpp', 'Zaawansowane programowanie w C++')], max_length=200, verbose_name='Przedmiot'),
        ),
    ]
